version: '3.3'

services:
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: bidstake
    volumes:
      - .:/bidstake
    ports: 
      - "8000:8000"