# Generated by Django 5.0.3 on 2024-06-01 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_current_bid_alter_bid_bid_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(default='default address', max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='year_built',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)]),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_images/')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.listing')),
            ],
        ),
    ]
